### ISSUE TITLE
zlzp-xx.js中request的一些问题

### ISSUE THREAD

**Issue by zurmokeeper** [LonHon/node.js#1]
```
request(prox, function (err, res, body) {
        if (err) {
            console.log('err:'+ipacc);    // 这里没有执行，程序就停了
            ipacc++;
            getHtml(url);
        } else {
            ipacc = 0;
            filterHtml(body,url);
        }
    })
```
请问您有没有遇到使用 `request `爬取页面的时候，程序爬着爬着就停了的情况，就是控制台一直在打印我自己写的日志，在爬取数据，然后突然光标就不动，但是却没有报错。整个程序就不动了。我是拿您的这个代码改的。我把代理去掉了。Node.js的版本是v6.9.0.系统是Win10.我爬的是豆瓣的页面，豆瓣都是https的，基本运行一次只能爬个200张帖子就停了。求解？

**Comment by LonHon** [comment]
如果没用代理的话应该是被反爬导致请求搁置，之前爬豆瓣电影(douban_film)时遇到过这种问题。
另外更新了下文件，你看下off分支

**Comment by zurmokeeper** [comment]
您的意思已经解决这个问题了吗？off分支的新代码？

**Comment by xcondor** [comment]
npm install 没有依赖可安装呢？
